name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions: write-all    

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file myNodejsContainer/Dockerfile --tag my-image-name

    - name: Run Microsoft DevOps Security
      uses: microsoft/security-devops-action@preview
      env:
        TRIVY_ACTION: 'image'
        TRIVY_TARGET: 'my-image-name'
      id: msdo
      with:
        tools: 'trivy'
        
      # Upload alerts to the Security tab
    - name: Upload alerts to Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}

    - name: Upload alerts file as a workflow artifact
      uses: actions/upload-artifact@v3
      with:  
        name: alerts
        path: ${{ steps.msdo.outputs.sarifFile }}
