name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file myNodejsContainer/Dockerfile --tag my-image-name

    - name: Run Microsoft DevOps Security
      uses: microsoft/security-devops-action@preview
      env:
        TRIVY_ACTION: 'image'
        TRIVY_TARGET: 'my-image-name'
      id: msdo
      with:
        tools: 'trivy'
